### ISSUE TITLE
'flutter packages get' always not responding.

### ISSUE THREAD

**Issue by arden** [davidmarne/flutter_built_redux#27]
when i'm use flutter_built_redux, and flutter packages get, it's always not responding.

i'm use flutter 3.1 beta.

**Comment by davidmarne** [comment]
It resolves for me on 3.1 beta. Can you post your pubspec.yaml please?

**Comment by arden** [comment]
```
name: saytoken_flutter
description: SayToken Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #dio: ^0.0.6
  intl: ^0.15.6
  cupertino_icons: ^0.1.0
  device_info: 0.2.0
  fluro: ^1.3.1
  json_serializable: ^0.5.0
  json_annotation: ^0.2.3
  redux: ^3.0.0
  flutter_redux: ^0.5.0
  flutter_built_redux: ^0.5.0
  #built_redux: ^7.4.0
  #built_value: ^5.0.0
  #built_collection: ^3.0.0
  #built_viewmodel: ^1.2.2
  shared_preferences: ^0.4.0
  flutter_secure_storage: ^3.0.0
  connectivity: ^0.3.0
  uuid: ^1.0.0
  quiver: ^0.29.0+1
  #mqtt_client: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
```
